# -*- coding: utf-8 -*-
# :Project:   pglast -- Travis CI configuration
# :Created:   lun 07 ago 2017 00:44:48 CEST
# :Author:    Lele Gaifax <lele@metapensiero.it>
# :License:   GNU General Public License version 3 or later
# :Copyright: Â© 2017, 2018, 2019 Lele Gaifax
#

language: python
python: "3.6"

matrix:
  include:
    - sudo: required
      services:
        - docker

env:
  global:
    - CIBW_TEST_REQUIRES="coverage pytest pytest-cov"
    - CIBW_TEST_COMMAND="py.test {project}/tests"
    - CIBW_SKIP="cp2* cp33* cp34*"
    - TWINE_USERNAME=lelit
      # Note: TWINE_PASSWORD is set in Travis settings

install: pip install -r requirements-test.txt

script:
  - pip install cibuildwheel==0.10.2
  - cibuildwheel --output-dir wheelhouse
  - |
    if [[ $TRAVIS_TAG ]]; then
      pip install twine
      twine upload wheelhouse/*.whl
    fi
